#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEB6CCA1483FA74EC (infra-root@openstack.org)
#
Name     : python-saharaclient
Version  : 1.2.0
Release  : 39
URL      : http://tarballs.openstack.org/python-saharaclient/python-saharaclient-1.2.0.tar.gz
Source0  : http://tarballs.openstack.org/python-saharaclient/python-saharaclient-1.2.0.tar.gz
Source99 : http://tarballs.openstack.org/python-saharaclient/python-saharaclient-1.2.0.tar.gz.asc
Summary  : Client library for Sahara API
Group    : Development/Tools
License  : Apache-2.0
Requires: python-saharaclient-python
Requires: Babel
Requires: keystoneauth1
Requires: osc-lib
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: python-openstackclient
Requires: requests
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
========================
Team and repository tags
========================
.. image:: http://governance.openstack.org/badges/python-saharaclient.svg
:target: http://governance.openstack.org/reference/tags/index.html

%package python
Summary: python components for the python-saharaclient package.
Group: Default

%description python
python components for the python-saharaclient package.


%prep
%setup -q -n python-saharaclient-1.2.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492029551
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1492029551
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
